name: Container Vulnerability Scan using trivy

on:
  push:
    branches:
      - main  # Trigger action when changes are pushed to the main branch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx (for multi-platform support)

      - name: Build the Docker image
        run: |
         docker build -t vulnerable-python-app -f vulnerable-python-app/Dockerfile vulnerable-python-app/  # Build the Docker image from the Dockerfile inside the vulnerable-python-app folder
      - name: Scan for vulnerabilities using Trivy
        uses: aquasecurity/trivy-action@master  # Trivy GitHub Action for scanning Docker images
        with:
          image-ref: 'vulnerable-python-app'
          format: 'json'
          output: 'trivy-report.json'
          severity: 'CRITICAL,HIGH'
 
      # Step 5: Configure SSH for EC2
      - name: Configure SSH for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts
 
      # Step 6: Push report to EC2 instance
      - name: Push report to EC2 instance
        run: |
          scp -i private_key.pem \
          trivy-report.json azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/vulnerabilities/
 
      # Step 7: Send Slack Notification with Build Status and Report
      - name: Send Slack Notification
        if: always()  # Send notification regardless of success or failure
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: '#channeltesting'  # Replace with your actual Slack channel name or ID
          message-format: |
            {
              "text": "Build Status Update",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#36a64f' || '#ff0000' }}",
                  "fields": [
                    {
                      "title": "Job Status",
                      "value": "${{ job.status }}",
                      "short": true
                    },
                    {
                      "title": "Report Location",
                      "value": "The report has been pushed to EC2 at `/home/azureuser/vulnerabilities/trivy-report.json`.",
                      "short": false
                    }
                  ]
                }
              ]
            }