name: Container Vulnerability Scan & Report

on:
  push:
    branches:
      - main

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1-6 remain exactly the same as your original workflow
      # ... [previous steps unchanged] ...

      # Step 7: Fixed Slack Notification
      - name: Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Container Scan Report :docker:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n${{ job.status == 'success' && ':white_check_mark: SUCCESS' || ':x: FAILURE'}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Date:*\n$(date +'%Y-%m-%d %H:%M:%S %Z')"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Report Location:*\n`/home/azureuser/vulnerabilities/trivy-report.json`"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*GitHub Actions:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run Details>"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }