name: Container Vulnerability Scan & Report

on:
  push:
    branches:
      - main

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t vulnerable-python-app \
          -f vulnerable-python-app/Dockerfile \
          vulnerable-python-app/

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'vulnerable-python-app'
          format: 'json'
          output: 'trivy-report.json'
          severity: 'CRITICAL,HIGH'

      - name: Configure SSH for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Push report to EC2 instance
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no \
          trivy-report.json azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/vulnerabilities/

      - name: Slack Notification
        if: always()  # Send notification even if previous steps fail
        run: |
          STATUS="${{ job.status }}"
          COLOR=#36a64f
          [ "$STATUS" = "success" ] || COLOR=#ff0000
          
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"attachments\": [{
              \"color\": \"$COLOR\",
              \"blocks\": [{
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"*Trivy Scan Status*: \`$STATUS\`\n*Branch*: \`${{ github.ref }}\`\n*Report Path*: \`/home/azureuser/vulnerabilities/trivy-report.json\`\"
                }
              }]
            }]
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
