name: Container Vulnerability Scan

on:
  push:
    branches:
      - main  # Trigger action when changes are pushed to the main branch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx (for multi-platform support)

      - name: Build the Docker image
        run: |
          docker build -t vulnerable-python-app .  # Build the Docker image from the Dockerfile

      - name: Scan for vulnerabilities using Trivy
        uses: aquasecurity/trivy-action@master  # Trivy GitHub Action for scanning Docker images
        with:
          image-ref: 'vulnerable-python-app'  # Name of the built Docker image
          format: 'table'  # Output format of the vulnerability scan (table, json, sarif, etc.)
          exit-code: '1'  # Fail the build if vulnerabilities are found
          severity: 'CRITICAL,HIGH'  # Only fail on critical and high vulnerabilities



