name: Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build -t vulnerable-python-app -f vulnerable-python-app/Dockerfile vulnerable-python-app/

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.41.0/trivy_0.41.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.41.0_Linux-64bit.deb

      - name: Run Trivy scan and generate report
        run: trivy image --format json --output trivy-report.json --severity CRITICAL,HIGH vulnerable-python-app

      - name: Attach report for debugging
        run: cat trivy-report.json

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2
        with:
          slack-message: |
            *Build Status:* ${{ job.status }}
            Vulnerability report has been generated.
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: '#vulnerability-reports'
          upload-file: trivy-report.json
          file-title: trivy-report.json
          file-type: json
