name: Container Vulnerability Scan using Trivy

on:
  push:
    branches:
      - main  # Trigger action when changes are pushed to the main branch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx (for multi-platform support)

      - name: Build the Docker image
        run: |
         docker build -t vulnerable-python-app -f vulnerable-python-app/Dockerfile vulnerable-python-app/  # Build the Docker image from the Dockerfile inside the vulnerable-python-app folder

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.41.0/trivy_0.41.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.41.0_Linux-64bit.deb

      - name: Scan for vulnerabilities using Trivy
        uses: aquasecurity/trivy-action@master  # Trivy GitHub Action for scanning Docker images
        with:
          image-ref: 'vulnerable-python-app'
          format: 'json'
          output: 'trivy-report.json'
          severity: 'CRITICAL,HIGH'

      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Configure SSH for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Push report to EC2 instance
        run: |
          # Get the current date in the format DD_MM_YYYY
          DATE=$(date +"%d_%m_%Y")
          REPORT_FILE="vulnerabilities_${DATE}.json"
          
          # Rename the fetched Trivy report to match the desired filename
          mv trivy-report.json $REPORT_FILE
          
          # Push the renamed file to EC2
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $REPORT_FILE azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/reports/

      - name: Upload the created file to Slack channel
        run: |
          # Get the current date in the format DD_MM_YYYY
          DATE=$(date +"%d_%m_%Y")
          REPORT_FILE="vulnerabilities_${DATE}.json"
          
          # Check if the file exists before attempting to upload
          if [ -f "/home/azureuser/reports/$REPORT_FILE" ]; then
            echo "File exists, uploading to Slack..."
            
            # Upload the file to Slack
            curl -F file=@"/home/azureuser/reports/$REPORT_FILE" \
              -F "initial_comment=Trivy Vulnerability Scan Report" \
              -F channels="#vulnerability-reports" \
              -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
              https://slack.com/api/files.upload
          else
            echo "File does not exist, skipping upload."
          fi
        shell: /usr/bin/bash -e {0}
        env:
          TRIVY_SEVERITY: CRITICAL,HIGH
          TRIVY_FORMAT: json
          TRIVY_OUTPUT: trivy-report.json
