name: Container Vulnerability Scan using trivy

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          docker build -t vulnerable-python-app -f vulnerable-python-app/Dockerfile vulnerable-python-app/

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.41.0/trivy_0.41.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.41.0_Linux-64bit.deb

      - name: Run Trivy scan and generate report
        run: trivy image --format json --output trivy-report.json --severity CRITICAL,HIGH vulnerable-python-app

      - name: Set job status variable
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "JOB_STATUS=Passed" >> $GITHUB_ENV
          else
            echo "JOB_STATUS=Failed" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          payload: |
            {
              "text": "Container Vulnerability Scan Results",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Build Status:* ${{ env.JOB_STATUS }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Vulnerability report is attached."
                  }
                }
              ],
              "file": "@trivy-report.json",
              "channels": "#vulnerability-reports"
            }
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: '#vulnerability-reports'
          upload-file: trivy-report.json
          file-title: trivy-report.json
          file-type: json
