name: Container Vulnerability Scan & Report

on:
  push:
    branches:
      - main

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t vulnerable-python-app \
          -f vulnerable-python-app/Dockerfile \
          vulnerable-python-app/

      # Step 4: Run Trivy scan (output: JSON + table for logs)
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'vulnerable-python-app'
          format: 'json'
          output: 'trivy-report.json'
          severity: 'CRITICAL,HIGH'

      # Step 5: Configure SSH for Azure VM
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      # Step 6: Push report to Azure VM
      - name: Push report to Azure VM
        run: |
          scp -i private_key.pem \
          trivy-report.json azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/vulnerabilities/

      # Step 7: Slack Notification (Enhanced)
      - name: Slack Notification
        if: always()  # Runs even if previous steps fail
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: '#vulnerabilities'  # Replace with your channel
          message-format: |
            {
              "text": "*Container Scan Report*",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#36a64f' || '#ff0000' }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Status*: ${{ job.status == 'success' && ':white_check_mark: SUCCESS' || ':x: FAILURE' }}\n*Date*: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Report Location*: `/home/azureuser/vulnerabilities/trivy-report.json`"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*GitHub Actions Run*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"
                      }
                    }
                  ]
                }
              ]
            }