name: Container Vulnerability Scan & Report

on:
  push:
    branches:
      - main

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t vulnerable-python-app \
          -f vulnerable-python-app/Dockerfile \
          vulnerable-python-app/

      # Step 4: Run Trivy vulnerability scan
      - name: Run Trivy vulnerability scan
        id: trivy-scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'vulnerable-python-app'
          format: 'json'
          output: 'trivy-report.json'
          severity: 'CRITICAL,HIGH'

      # Step 5: Configure SSH for EC2
      - name: Configure SSH for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      # Step 6: Push report to EC2 instance
      - name: Push report to EC2 instance
        run: |
          scp -i private_key.pem \
          trivy-report.json azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/vulnerabilities/

      # Step 7: Send Slack Notification using Webhook
      - name: Send Slack Notification
        if: always()  # Run regardless of job status
        run: |
          STATUS="${{ job.status }}"
          COLOR="#36a64f" # Green for success
          if [ "$STATUS" == "failure" ]; then
            COLOR="#ff0000" # Red for failure
          fi
          
          MESSAGE="Build Status: $STATUS\nReport pushed to EC2 at /home/azureuser/vulnerabilities/trivy-report.json"
          
          curl -X POST -H 'Content-type: application/json' --data "{
            \"channel\": \"#saikrishna11\",
            \"attachments\": [
              {
                \"color\": \"$COLOR\",
                \"text\": \"$MESSAGE\"
              }
            ]
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
