name: Container Vulnerability Scan

on:
  push:
    branches:
      - main  # Trigger action when changes are pushed to the main branch

jobs:
  scan:
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker for building the image
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t vulnerable-python-app -f vulnerable-python-app/Dockerfile vulnerable-python-app/

      # Scan the Docker image for vulnerabilities using Trivy
      - name: Scan for vulnerabilities using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-python-app'  # The Docker image to be scanned
          format: 'json'  # Output format as JSON
          output: 'trivy-report.json'  # Store the Trivy scan report in this file
          severity: 'CRITICAL,HIGH'  # Scan for critical and high severity vulnerabilities
        # Do not fail the job on vulnerabilities (No exit-code set, so the pipeline continues)

      # Send the Trivy report to Slack channel named "vulneribilities"
      - name: Send Trivy report to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data @trivy-report.json ${{ secrets.SLACK_WEBHOOK_URL }}

      # Push the Trivy report to the EC2 instance for Prometheus storage
      - name: Push Trivy report to EC2 for Prometheus
        run: |
          # Create the target directory on the EC2 instance (if it doesn't exist)
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_IP }} "mkdir -p /home/ubuntu/trivy-reports/"

          # Copy the Trivy report to the EC2 instance
          scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} trivy-report.json ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/trivy-reports/

          # (Optional) You can also push to a Prometheus-compatible location if needed
          # Example: scp -i ${{ secrets.EC2_SSH_KEY }} trivy-report.json ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/prometheus/data/
