name: Trivy Scan and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  trivy-scan-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Run Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'  # File system scan
          format: 'json'
          output: 'report.json'
          severity: 'CRITICAL,HIGH'

      # Step 3: Set up SSH for EC2 access
      - name: Configure SSH
        run: |
          echo "${{ secrets.AZURE_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # Step 4: Copy report to EC2 instance
      - name: Push report to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no report.json azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/vulnerabilities/

      # Step 5: Send Slack notification
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Trivy scan completed and report pushed to EC2."}' ${{ secrets.SLACK_WEBHOOK_URL }}
