name: Container Vulnerability Scan

on:
  push:
    branches:
      - main  # Trigger action when changes are pushed to the main branch

jobs:
  scan:
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker for building the image
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t vulnerable-python-app -f vulnerable-python-app/Dockerfile vulnerable-python-app/

      # Scan the Docker image for vulnerabilities using Trivy
      - name: Scan for vulnerabilities using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-python-app'  # The Docker image to be scanned
          format: 'json'  # Output format as JSON
          output: 'trivy-report.json'  # Store the Trivy scan report in this file
          severity: 'CRITICAL,HIGH'  # Scan for critical and high severity vulnerabilities
        continue-on-error: true  # This ensures the pipeline continues even if vulnerabilities are found

      # Send the Trivy report to Slack channel named "vulneribilities"
      - name: Send Trivy report to Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          fields: |
            {
              "title": "Trivy Scan Report",
              "value": "The Trivy scan report is attached.",
              "short": false
            }
          file: trivy-report.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Push the Trivy report to the Azure VM for Prometheus storage
      - name: Push Trivy report to Azure VM for Prometheus
        run: |
          # Create the target directory on the Azure VM (if it doesn't exist)
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AZURE_SSH_KEY }} azureuser@${{ secrets.AZURE_VM_IP }} "mkdir -p /home/azureuser/trivy-reports/"

          # Copy the Trivy report to the Azure VM
          scp -o StrictHostKeyChecking=no -i ${{ secrets.AZURE_SSH_KEY }} trivy-report.json azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/trivy-reports/
